apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdfsimple.fullname" . }}-backend
  labels:
    {{- include "pdfsimple.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pdfsimple.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdfsimple.fullname" . }}-frontend
  labels:
    {{- include "pdfsimple.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pdfsimple.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
